CREATE TABLE [Events] (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [Name] NVARCHAR (150) NOT NULL,
    [Date] DATETIME NOT NULL,
    [Location] NVARCHAR(255) NOT NULL,
    [Info] NVARCHAR(1500) NOT NULL,
	[StartTime] NVARCHAR(30) NOT NULL,
	[EndTime] NVARCHAR(30)
);

CREATE TABLE [Users](
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [Email] NVARCHAR(150) NOT NULL,
    [Password] NVARCHAR(150) NOT NULL,
    [PhoneNumber] NVARCHAR(20)NOT NULL,
    [UserType] NVARCHAR(20) NOT NULL,
	[Name] NVARCHAR(150) NOT NULL
)

CREATE TABLE [EmsInEvent](
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [EventID] INT NOT NULL FOREIGN KEY (EventId) REFERENCES Events(ID),
    [EmID] INT NOT NULL FOREIGN KEY (EmID) REFERENCES Users(ID)
);

CREATE TABLE TicketsInEvent(
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [EVENTID] INT FOREIGN KEY (EVENTID) REFERENCES Events([ID]),
    [BARCODE] NVARCHAR(30) FOREIGN KEY ([BARCODE]) REFERENCES Tickets([BARCODE])
)