USE [EvenTOP]
GO

/****** Object:  Table [dbo].[EmsInEvent]    Script Date: 20/04/2022 22:32:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EmsInEvent](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EventID] [int] NOT NULL,
	[EmID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EmsInEvent]  WITH CHECK ADD FOREIGN KEY([EventID])
REFERENCES [dbo].[Events] ([ID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[EmsInEvent]  WITH CHECK ADD FOREIGN KEY([EmID])
REFERENCES [dbo].[Users] ([ID]) ON DELETE CASCADE
GO


