USE [EvenTOP]
GO

/****** Object:  Table [dbo].[TicketsRS]    Script Date: 19/04/2022 17:29:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TicketsRS](
	[BARCODE] [nvarchar](100) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE] [nvarchar](30) NOT NULL,
	[EXTRAS] [nvarchar](100) NULL,
	[STARTTIME] [nvarchar](30) NULL,
	[ENDTIME] [nvarchar](30) NULL,
	[ROW] [int] NOT NULL,
	[SEAT] [int] NOT NULL,
	[EVENTID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TicketsRS]  WITH CHECK ADD FOREIGN KEY([BARCODE])
REFERENCES [dbo].[Tickets] ([BARCODE]) ON DELETE CASCADE
GO


